Feat/token list migration
hummingbot/gateway pull request #155
Opened 2023-07-12 14:22 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Copies token lists over from template directory to the conf directory.
PR for https://github.com/hummingbot/gateway/issues/148

**Tests performed by the developer**:
- Manual test

**Tips for QA testing**:
- Run usual yarn commands to setup gateway.
 - At `yarn build` the token files should be copied over.

2023-07-12 14:23 UTC, vic-en commented on gateway-setup.sh
> +  cp -rf $TEMPLATE_DIR/lists $HOST_CONF_PATH
```suggestion
  cp -rf $TEMPLATE_DIR/ $HOST_CONF_PATH
```

2023-07-13 08:28 UTC, rapcmia commented
PR update:
- Test latest commit `5631e235`
- Test on local mbp(m1) and Ubuntu22.04 server
- Test this PR and latest development client branch 

Run `yarn && yarn build` and observed:
![image](https://github.com/hummingbot/gateway/assets/73840223/89fed25e-e680-4a59-a987-ed74f9242b68)
- This does not seem to copy anything to the `conf/list` even we change the permission `sudo chmod 777 conf/list` and re-run `yarn build` for both local and cloud 

---

Test on local mbp(m1)
![image](https://github.com/hummingbot/gateway/assets/73840223/6961b808-e3ec-4830-a883-706a4f948fba)
- Observed that it was only able to copy these `lists/*.json files` from `templates/lists` when we ran `gateway-setup.sh`

---

Test on Ubuntu22.04 cloud server
- We recorded the steps here on the loom video where it does not copy *.json files to conf/lists folder for both `yarn build` and `gateway-setup.sh` script
- https://www.loom.com/share/26f531b67c2c4908be8f36ac25b5174c

2023-07-14 00:05 UTC, fengtality requested changes
See other PR

2023-07-14 00:05 UTC, fengtality commented on package.json
> +    "copy-files:token-list": "mkdir -p conf/lists && copyfiles -u 'src/templates/lists/*.json' conf/lists",
I think this works if you change `-u` to `-f` here

2023-07-14 06:00 UTC, closed without merging