Feat/token list migration
hummingbot/gateway pull request #159
Opened 2023-07-14 00:07 UTC by fengtality

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Revised version of https://github.com/hummingbot/gateway/pull/155

**Tests performed by the developer**:

**Tips for QA testing**:

2023-07-14 04:06 UTC, rapcmia approved these changes
LGTM

- Revision of PR155, test latest commit 9451a6d2b7469b
- Run `yarn build` then check `conf/lists` folder, all ok ✅
   ![image](https://github.com/hummingbot/gateway/assets/73840223/98bf3f7e-af82-45e7-8d15-92fbb20a9ad4)
- Deleted `conf` folder and observe changes on `gateway-setup.sh`, all ok ✅ 
  ![image](https://github.com/hummingbot/gateway/assets/73840223/49449515-8581-480c-bf61-2281f6d2e7b9)
- Ran tests on both local mbp(m1) and Ubuntu22.04 test server

2023-07-14 15:48 UTC, rapcmia commented
PR update for docker build 
-  Create docker image for this PR and latest client development branch 

Using `hummigbot_gateway-compose`
- Use latest commit for deploy_examples repo 
- Setup hummingbot_gateway_compose file then `docker compose up -d`
    ![image](https://github.com/hummingbot/gateway/assets/73840223/748afe1e-f550-4c08-b529-0fa4ee3970b2)
    - On the screenshot above, either `list` or `lists` is not available
    - Added docker compose file 👀 
      ```
      version: "3.9"
        services:
          hummingbot:
            container_name: hummingbot1
            image: hummingbot/hummingbot:dev
            volumes:
              - "./hummingbot_files/conf:/home/hummingbot/conf"
              - "./hummingbot_files/conf/connectors:/home/hummingbot/conf/connectors"
              - "./hummingbot_files/conf/strategies:/home/hummingbot/conf/strategies"
              - "./hummingbot_files/logs:/home/hummingbot/logs"
              - "./hummingbot_files/data:/home/hummingbot/data"
              - "./hummingbot_files/scripts:/home/hummingbot/scripts"
              - "./hummingbot_files/certs:/home/hummingbot/certs"
            # environment:
            #   - CONFIG_PASSWORD=test
            logging:
              driver: "json-file"
              options:
                  max-size: "10m"
                  max-file: "5"
            tty: true
            stdin_open: true
            network_mode: host
        
          gateway:
            container_name: gateway1
            image: hummingbot/gateway:159
            ports:
              - "15888:15888"
              - "8080:8080"
            volumes:
              - "./gateway_files/conf:/home/gateway/conf"
            #  - "./gateway_files/conf/lists:/home/gateway/conf/lists" 
              - "./gateway_files/logs:/home/gateway/logs"
              - "./gateway_files/db:/home/gateway/db"
              - "./hummingbot_files/certs:/home/gateway/certs"
            # environment:
            #   - GATEWAY_PASSPHRASE=a
      ```
      - Added `conf/lists` on the file for test purpose
      - Change folder permission as well and check `conf/lists` still empty

---

Ran tests using `gateway-create.sh`
- Follow the prompts and use PR docker image ✅ 
  ![image](https://github.com/hummingbot/gateway/assets/73840223/83508e06-bafb-4d6e-8356-ae0e7bb4823a)

2023-07-15 08:19 UTC, vic-en requested changes
@fengtality 
Docker and source will work after those suggestions are commited.

1. It's advisable to remove the `copy_lists` function in the gateway-setup.sh files.
2. [Set 3](https://github.com/hummingbot/deploy-examples/blob/main/hummingbot_gateway_compose/README.md#3-add-token-lists)  of docker compose file for gateway can be removed as well.

I couldn't push commits because the pr was re-created.

2023-07-15 08:19 UTC, vic-en commented on package.json
> +    "prebuild": "rimraf dist && mkdir dist && yarn copy-files:token-list",
```suggestion
    "prebuild": "rimraf dist && mkdir dist",
```

2023-07-15 08:19 UTC, vic-en commented on package.json
> +    "copy-files:token-list": "mkdir -p conf/lists && copyfiles -f 'src/templates/lists/*.json' conf/lists",
```suggestion
    "copy-files:token-list": "mkdir -p conf/lists && copyfiles -f -s 'src/templates/lists/*.json' conf/lists",
```

2023-07-15 08:19 UTC, vic-en commented on package.json
>      "start": "/bin/bash ./startup.sh",
```suggestion
    "start": "yarn copy-files:token-list && /bin/bash ./startup.sh",
```

2023-07-15 23:26 UTC, fengtality commented
Closed in favor of #160

2023-07-15 23:26 UTC, closed without merging