feat/ Osmosis Chain/Connector
hummingbot/gateway pull request #277
Opened 2024-01-30 21:32 UTC by nkhrs

Before submitting this PR, please make sure:

[x ] Your code builds clean without any errors or warnings
[x ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

A description of the changes proposed in the pull request:
Adds Osmosis (with LP) support as a chain, plus some updates to Cosmos chain.

Cosmos amm.routes.ts models don't match up well with the rest due to inherent differences in their data. This has been handled by allowing certain endpoints to receive Cosmos-specific models switched by chain, eg. AddLiquidityRequest | CosmosAddLiquidityRequest.

Docs for above endpoints are in Swagger now.

Tests performed by the developer:
Jest tests added for all Osmosis functions. Very little patch use, instead a testnet wallet is instantiated and trades/liquidity actions are performed with it.
yarn test:cov is ~80% for Osmosis, improved for Cosmos.

Tips for QA testing:
THIS LINE MUST to be added to HBOT client native_tokens[]
"osmosis": "OSMO",
in hummingbot/core/utils/gateway_config_utils.py

PR has been submitted to HBOT main for that file as well.

2024-02-02 18:17 UTC, fengtality commented
Please resolve conflicts as we just merged in another DEX connector

2024-02-02 18:55 UTC, fengtality requested changes
Please ma

2024-02-02 18:55 UTC, fengtality commented on src/amm/amm.requests.ts
>  export interface PoolPriceRequest extends NetworkSelectionRequest {
revert back to `CosmosPoolPriceRequest` interface

2024-02-02 18:55 UTC, fengtality commented on src/amm/amm.requests.ts
>  export interface PoolPriceResponse {
revert back to `CosmosPoolPriceResponse` interface

2024-02-02 18:55 UTC, fengtality commented on src/amm/amm.requests.ts
> +export interface AddLiquidityRequest extends NetworkSelectionRequest { // now also cosmos add swap position OR cosmos add LP position
revert back to `CosmosAddLiquidityRequest ` interface

2024-02-02 18:55 UTC, fengtality commented on src/amm/amm.requests.ts
>  export interface AddLiquidityResponse {
revert back to `Cosmos AddLiquidityResponse ` interface

2024-02-02 18:55 UTC, fengtality commented on src/amm/amm.requests.ts
>  export interface RemoveLiquidityRequest extends CollectEarnedFeesRequest {
revert back to `Cosmos RemoveLiquidityRequest ` interface

2024-02-02 18:55 UTC, fengtality commented on src/amm/amm.requests.ts
>  export interface RemoveLiquidityResponse {
revert back to `CosmosRemoveLiquidityResponse ` interface

2024-02-14 17:39 UTC, fengtality commented
@nkhrs As mentioned on Discord, the additions to the LP interfaces are fine. 

To wrap up this PR: please move the Osmosis chain tests to the /test-bronze folder, and address any unit test failures due to interface changes. After that, LGTM!

2024-02-15 22:26 UTC, chasevoorhees commented
> @nkhrs As mentioned on Discord, the additions to the LP interfaces are fine.
> 
> To wrap up this PR: please move the Osmosis chain tests to the /test-bronze folder, and address any unit test failures due to interface changes. After that, LGTM!

All done

2024-02-16 00:21 UTC, fengtality approved these changes

2024-02-16 14:53 UTC, fengtality commented
@chasevoorhees we merged in a fix to the XRPL connector - can you check and resolve conflicts?

Also, are the failing unit tests below related to the V3 interface changes?

```
FAIL test/connectors/pancakeswap/pancakeswap.lp.routes.test.ts (7.662 s)
  ● POST /liquidity/position › should return 200 when all parameter are OK

    expected 200 "OK", got 404 "Not Found"

      368 |       })
      369 |       .set('Accept', 'application/json')
    > 370 |       .expect(200);
          |        ^
      371 |   });
      372 |
      373 |   it('should return 404 when the tokenId is invalid', async () => {

      at test/connectors/pancakeswap/pancakeswap.lp.routes.test.ts:370:8
      at test/connectors/pancakeswap/pancakeswap.lp.routes.test.ts:8:71
      at Object.<anonymous>.__awaiter (test/connectors/pancakeswap/pancakeswap.lp.routes.test.ts:4:12)
      at Object.<anonymous> (test/connectors/pancakeswap/pancakeswap.lp.routes.test.ts:354:64)
      ----
      at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
      at node_modules/supertest/lib/test.js:308:13
      at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
      at Test.assert (node_modules/supertest/lib/test.js:164:23)
      at Server.localAssert (node_modules/supertest/lib/test.js:120:14)

FAIL test/connectors/uniswap/uniswap.lp.routes.test.ts (7.832 s)
  ● POST /liquidity/position › should return 200 when all parameter are OK

    expected 200 "OK", got 404 "Not Found"

      368 |       })
      369 |       .set('Accept', 'application/json')
    > 370 |       .expect(200);
          |        ^
      371 |   });
      372 |
      373 |   it('should return 404 when the tokenId is invalid', async () => {

      at test/connectors/uniswap/uniswap.lp.routes.test.ts:370:8
      at test/connectors/uniswap/uniswap.lp.routes.test.ts:8:71
      at Object.<anonymous>.__awaiter (test/connectors/uniswap/uniswap.lp.routes.test.ts:4:12)
      at Object.<anonymous> (test/connectors/uniswap/uniswap.lp.routes.test.ts:354:64)
      ----
      at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
      at node_modules/supertest/lib/test.js:308:13
      at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
      at Test.assert (node_modules/supertest/lib/test.js:164:23)
      at Server.localAssert (node_modules/supertest/lib/test.js:120:14)


Test Suites: 2 failed, 31 passed, 33 total
Tests:       2 failed, 375 passed, 377 total
Snapshots:   0 total
Time:        241.812 s
Ran all test suites matching /.\/test\//i.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
```

2024-02-16 15:58 UTC, chasevoorhees commented
> @chasevoorhees we merged in a fix to the XRPL connector - can you check and resolve conflicts?
done - someone committed the package.lock with a non-standard (OSX I think) cache directory.

> Also, are the failing unit tests below related to the V3 interface changes?

Seems to be a validation issue. 

`"Error: The request is missing the key: address\n    at throwIfErrorsExist (/home/vboxuser/hbot/pecugateway-dev/gateway/dist/src/services/validators.js:38:15)\n    at /home/vboxuser/hbot/pecugateway-dev/gateway/dist/src/services/validators.js:103:40\n    at /home/vboxuser/hbot/pecugateway-dev/gateway/dist/test/chains/osmosis/osmosis.testnojest.js:86:58\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/vboxuser/hbot/pecugateway-dev/gateway/dist/test/chains/osmosis/osmosis.testnojest.js:5:58)"`

I had added validateAddress to validatePositionRequest (I think you told me that it wouldn't throw if the arg wasn't required). Just going to remove that bit for now since it's throwing everywhere all the sudden.

We're good, now.

2024-02-26 19:38 UTC, chasevoorhees commented
@rapcmia 

Any update for us?

Also this is the main client PR: https://github.com/hummingbot/hummingbot/pull/6685 - it adds OSMO to native_tokens_list and creates the base Osmosis strategy gateway_osmosis_amm_lp.py

2024-02-27 07:24 UTC, rapcmia commented
PR update:
- Ran test `a64d5090fe52adfd3dab401aea5441989557698f`
- Setup both PR and gateway connection ok
- Ran API tests:
  - Check port connection ok
  - Check list of connectors, osmosis ok
  - Add, get and remove osmosis wallet ok
  - Check balance, add tokens and displayed ok
  - Check status, returned Osmosis chain with nativeCurrency set to OSMO
  - Get tokens, ok
  - Get price buy and sell ok
  - Manually add liquidity and check position ok however:
    - When adding position getting `trade query failed - invalid coins `
      ![image](https://github.com/hummingbot/gateway/assets/73840223/87abec0d-15e1-4a39-994a-938df7b43899)
      - Check `conf/list/osmosis-1.assetlist.json`, compare tokens from txhash from manual position seems the same
      - Tried to use base names for the selected markets but got a different error which seems expected if not using the symbol names
---

Ran `amm_lp strategy` 
- Started ok with logs showing found pool for the selected market 
- Set tight min_profitability to check behavior when adding position
  ![image](https://github.com/hummingbot/gateway/assets/73840223/7378d124-52a3-4e28-ba07-afdd7344c23c)
    ```
    ::1 - - [27/Feb/2024:07:11:16 +0000] "POST /chain/balances HTTP/1.1" 200 125 "-" "Python/3.10 aiohttp/3.9.3"
    2024-02-27 08:31:19 | info |    Found pools and prices for DAI, OSMO.
    ::1 - - [27/Feb/2024:07:11:19 +0000] "POST /amm/liquidity/price HTTP/1.1" 200 2476 "-" "Python/3.10 aiohttp/3.9.3"
    2024-02-27 08:31:27 | info |    Found pools and prices for DAI, OSMO.
    ::1 - - [27/Feb/2024:07:11:27 +0000] "POST /amm/liquidity/price HTTP/1.1" 200 2476 "-" "Python/3.10 aiohttp/3.9.3"
    ::1 - - [27/Feb/2024:07:11:27 +0000] "POST /amm/liquidity/price HTTP/1.1" 200 2476 "-" "Python/3.10 aiohttp/3.9.3"
    TypeError: Cannot read properties of undefined (reading 'find')
        at extendPool (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.lp.utils.js:52:26)
        at /Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:1334:101
        at Array.map (<anonymous>)
        at Osmosis.<anonymous> (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:1334:53)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    2024-02-27 08:31:35 | error |   Trade query failed: 
    ::1 - - [27/Feb/2024:07:11:35 +0000] "POST /amm/liquidity/price HTTP/1.1" 500 432 "-" "Python/3.10 aiohttp/3.9.3"
    TypeError: Cannot read properties of undefined (reading 'find')
        at extendPool (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.lp.utils.js:52:26)
        at /Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:1334:101
        at Array.map (<anonymous>)
        at Osmosis.<anonymous> (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:1334:53)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    2024-02-27 08:31:43 | error |   Trade query failed: 
    ::1 - - [27/Feb/2024:07:11:43 +0000] "POST /amm/liquidity/price HTTP/1.1" 500 432 "-" "Python/3.10 aiohttp/3.9.3"
    ::1 - - [27/Feb/2024:07:11:46 +0000] "POST /chain/balances HTTP/1.1" 200 125 "-" "Python/3.10 aiohttp/3.9.3"
    TypeError: Cannot read properties of undefined (reading 'find')
        at extendPool (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.lp.utils.js:52:26)
        at /Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:1334:101
        at Array.map (<anonymous>)
        at Osmosis.<anonymous> (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:1334:53)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/rapcomia/github/gateway/277/dist/src/chains/osmosis/osmosis.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    2024-02-27 08:31:51 | error |   Trade query failed: 
    ```

Steps to reproduce:
- Setup the strategy or API tests that will add position on the selected market 
  - Use `POST https://{{host}}:{{port}}/amm/liquidity/add`
 
[logs_gateway_app.log.2024-02-27.log](https://github.com/hummingbot/gateway/files/14415800/logs_gateway_app.log.2024-02-27.log)

2024-02-27 09:00 UTC, chasevoorhees commented
>When adding position getting trade query failed - invalid coins 
Can you confirm if this was GAMM or CL?

That is the correct format for the coins there. I believe this error is returned by the RPC server when the ratio of the 2 coins added don't roughly match the ratio in the pool (so the dollar values should be similar).

Currently OSMO is trading at 1.63 DAI 
Please try 1.8OSMO 2.934DAI 
AddLiquidityResponse:
![image](https://github.com/hummingbot/gateway/assets/26911704/2444161a-6bbd-4cca-824c-2862ceafe8e6)


>TypeError: Cannot read properties of undefined (reading 'find')
This one appears to be caused by a failure to get the fees from this URL
https://api-osmosis.imperator.co/fees/v1/pools
Can you confirm you can access this address?

Here's what the whole chain from GET to that error looks like (and why I'm hoping it's a connection issue):
![image](https://github.com/hummingbot/gateway/assets/26911704/54cb3f4a-376e-42ee-baea-23bc60a65b2e)
![image](https://github.com/hummingbot/gateway/assets/26911704/0d4a67a8-d56b-43aa-af78-6937bb120bb5)
![image](https://github.com/hummingbot/gateway/assets/26911704/55bcc607-1d7e-4605-b7f7-b4fc45934048)


@nkhrs can you run test out DAI/OSMO in curl/the client as well?

2024-02-27 16:34 UTC, nikspz commented
@chasevoorhees Please resolve branch conflicts on this PR

2024-02-28 03:48 UTC, chasevoorhees commented
I was wrong about the invalid coins error - turns out it was angry about alphabetization, not ratio. Anyway, that's fixed.
I also fixed another RPC error due to the number of significant figures that DAI has.

**That should be all the issues you mentioned**, but I did see that .find/undefined error once on my side as well:

And it's definitely an issue with the API:
https://api-osmosis.imperator.co/fees/v1/pools
![image](https://github.com/hummingbot/gateway/assets/26911704/61d429a8-a3ef-48c9-9bd0-156d83e4bf4f)

It came back up pretty quickly, at least:
![image](https://github.com/hummingbot/gateway/assets/26911704/ed8b0ae5-b5e4-4017-94ec-b0bf8f4fa7ea)

When testing this, are you able to connect to a VPN in the EU? That might help, but **I've also made it just ignore fees when we can't access that endpoint** (fees will all appear as 0).

2024-02-28 07:10 UTC, rapcmia commented
Thanks for the update 🚀 
- Reported issue on invalid coins has been fixed
- Ran tests on other endpoints;
  - When insufficient funds, returns insufficient amount of token {0 or 1} created
  - Position retrieve pool data successfully
  - Remove position ok
- When running amm-lp strategy for osmosis, the Pool Price is `0`
  ![image](https://github.com/hummingbot/gateway/assets/73840223/9df1680a-4964-4e4d-acca-c0660f9096c4)
    - This time we use a different market to compare but same behavior
    - We tried to tunnel to UK to check if this helps the pool price but no go, tho we are able to see https://api-osmosis.imperator.co/fees/v1/pools

2024-02-28 23:00 UTC, chasevoorhees commented
I think it's fixed now - is it correct to assume that that's just the market price of the 2 coins?

Otherwise there's no way to get a price for a specific pool in Osmosis; as far as I can tell, the concept doesn't exist.

2024-02-29 03:53 UTC, rapcmia commented
Hi @chasevoorhees thanks for the update,
The amm-lp strategy is now trying to create position for the connector however we are getting error when adding liquidity:
```
2024-02-29 11:27:23,144 - 7772 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-02-29 11:27:23,356 - 7772 - GatewayOsmosisAMMLP - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-29 11:27:24,000 - 7772 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - WARNING - osmosis_osmosis_mainnet connector is not ready. Please wait...
2024-02-29 11:27:25,001 - 7772 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - INFO - osmosis_osmosis_mainnet connector is ready. Trading started.
2024-02-29 11:27:27,535 - 7772 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - INFO - Creating new position over 1.6063094809485383414370 to 1.6224532948274181237630 price range. [clock=2024-02-29 03:27:27+00:00]
2024-02-29 11:27:27,536 - 7772 - GatewayOsmosisAMMLP - ERROR - Error submitting ADD liquidity order to osmosis on mainnet for OSMO-USDC 
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 440, in _add_liquidity
    self.address0,
AttributeError: 'GatewayOsmosisAMMLP' object has no attribute 'address0'
```

2024-02-29 06:18 UTC, chasevoorhees commented
@rapcmia Yikes - that one's just a typo. Sorry.

https://github.com/pecuniafinance/hummingbot/blob/development/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py

Here's the updated file (also pushed to the repo above)

2024-02-29 22:15 UTC, chasevoorhees commented
@rapcmia 
Nik sent me some screenshots of the latest error
<img width="402" alt="image_2024-02-29_14-49-09" src="https://github.com/hummingbot/gateway/assets/26911704/b722883d-32d9-4b5f-94f9-c771505c49ce">

This is definitely slippage related - and actually the default allowedSlippage in osmosis.yml is pretty low:

allowedSlippage: 2%

You may need to set this around 40% for that transaction to go through, however **what this is actually used to calculate is the minimum amount of token you're willing to put into the pool**... so it's not really slippage, per se:

```
{
  typeUrl: "/osmosis.concentratedliquidity.v1beta1.MsgCreatePosition",
  value: {
    poolId: "1066",
    sender: "osmo1mvsg3en5ulpnpd3dset2m86zjpnzp4v4epmjh7",
    lowerTick: "400000",
    upperTick: "800000",
    tokensProvided: [
      {
        denom: "ibc/0CD3A0285E1341859B5E86B6AB7682F023D03E97607CCC1DC95706411D866DF7",
        amount: "293400000000000000",
      },
      {
        denom: "uosmo",
        amount: "180000",
      },
    ],
    tokenMinAmount0: "0",
    tokenMinAmount1: "0",
  },
}
```

This is my join pool message with slippage=100% (hence tokenMinAmount0/1 == 0)

Here's what I ended up putting into my pool:

```
token0_finalamount = "0"
token1_finalamount = "293400000000000000"
```

I believe this implies a value imbalance in the pool (in my case, there was already too much of token0 so it won't accept any more - previously I was getting this: "slippage bound: insufficient amount of token 0 created. Actual: (0). Minimum estimated: (234720000000000000)")

**Would you suggest that I set the minAmount to 0 for all cases and disregard slippage as used elsewhere?** Technically it's just the minimum amount you're willing to join the pool with.. And it's kind of confusing if it's sometimes going to be 0 for some tokens.

Anyway, if you set your allowedSlippage='100%' then you should be able to get past this.

I asked the Osmosis team about this one as well to confirm.

2024-02-29 22:16 UTC, chasevoorhees commented
I also read that you're having issues setting values through the client:
gateway config osmosis.feeTier
I'll test this on my side as well.. not sure where this value is stored, currently.

2024-03-01 06:47 UTC, chasevoorhees commented
![image](https://github.com/hummingbot/gateway/assets/26911704/42cbeefb-276e-4c40-852a-cf7b84207329)
I'm able to update that config var without issue.

2024-03-01 07:00 UTC, rapcmia commented
> This is definitely slippage related - and actually the default allowedSlippage in osmosis.yml is pretty low:
allowedSlippage: 2%

Hi @chasevoorhees thanks for checking, I change the `allowSlippage` from 2% to 50 and 100. Both seem work on amm-lp strategy and postman, we are able to add liquidity however its returning an error:
![image](https://github.com/hummingbot/gateway/assets/73840223/a5c57fc1-8482-4f0c-b039-6277086b3399)
![image](https://github.com/hummingbot/gateway/assets/73840223/8f079dc9-21bf-4fa6-aff5-7d5f2e7a5fb6)
- Getting Call to https://localhost:15888/amm/liquidity/add failed
```

2024-03-01 14:13:33,182 - 55688 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/liquidity/add failed. See logs for more details.
2024-03-01 14:13:33,183 - 55688 - GatewayOsmosisAMMLP - ERROR - Error submitting ADD liquidity order to osmosis on mainnet for OSMO-USDC 
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 436, in _add_liquidity
    order_result: Dict[str, Any] = await self._get_gateway_instance().amm_lp_add(
  File "/Users/rapcomia/github/hummingbot/6685/hummingbot/core/gateway/gateway_http_client.py", line 729, in amm_lp_add
    return await self.api_request("post", "amm/liquidity/add", request_payload)
  File "/Users/rapcomia/github/hummingbot/6685/hummingbot/core/gateway/gateway_http_client.py", line 222, in api_request
    raise e
  File "/Users/rapcomia/github/hummingbot/6685/hummingbot/core/gateway/gateway_http_client.py", line 210, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/amm/liquidity/add Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'TypeError: Do not know how to serialize a BigInt\n    at JSON.stringify (<anonymous>)\n    at stringify (/Users/rapcomia/github/gateway/277/node_modules/express/lib/response.js:1150:12)\n    at ServerResponse.json (/Users/rapcomia/github/gateway/277/node_modules/express/lib/response.js:271:14)\n    at /Users/rapcomia/github/gateway/277/dist/src/amm/amm.routes.js:42:25\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rapcomia/github/gateway/277/dist/src/amm/amm.routes.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
2024-03-01 14:13:33,186 - 55688 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1709273613.0, "order_id": "add-OSMO-USDC-1709273594617378", "order_action": "LPType.ADD", "event_name": "RangePositionUpdateFailureEvent", "event_source": "osmosis_osmosis_mainnet"}
```

[logs_ammlp-osmo.log](https://github.com/hummingbot/gateway/files/14457698/logs_ammlp-osmo.log)

2024-03-01 20:50 UTC, chasevoorhees commented
@rapcmia 

Good(ish) news, Osmo guys backed me up on the slippage issue:
![image](https://github.com/hummingbot/gateway/assets/26911704/17b4cd2f-1794-4c4e-a7ad-5e225afb6a3e)

Re: The BigInt error.. I have no idea how this one suddenly appeared again but it should be fixed now. 
Sorry about this... we've basically offloaded testing to you at this point. @nkhrs owes you a beer.

2024-03-04 03:22 UTC, rapcmia commented
- TypeError on BigInt has been fixed ✅
- Endpoints adding and removing works ok
- Ran connector on `amm-lp strategy`, created position successfully however this time we are getting `KeyError: 'txStatus'`
  ```
  2024-03-04 11:14:22,775 - 9162 - hummingbot.client.hummingbot_application - INFO - start command initiated.
  2024-03-04 11:14:22,807 - 9162 - GatewayOsmosisAMMLP - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-03-04 11:14:23,001 - 9162 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - WARNING - osmosis_osmosis_mainnet connector is not ready. Please wait...
  2024-03-04 11:14:24,001 - 9162 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - WARNING - osmosis_osmosis_mainnet connector is not ready. Please wait...
  2024-03-04 11:14:25,001 - 9162 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - INFO - osmosis_osmosis_mainnet connector is ready. Trading started.
  2024-03-04 11:14:26,976 - 9162 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - INFO - Creating new position over 1.59867495286045253462125 to 1.61474203781382391687875 price range. [clock=2024-03-04 03:14:26+00:00]
  2024-03-04 11:14:28,315 - 9162 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-03-04 11:14:45,434 - 9162 - GatewayOsmosisAMMLP - INFO - Created ADD liquidity order add-OSMO-USDC-1709522066976880 txHash: C22897750551744A141409CC4AE0B9A8AB9638FBB5622FC22CA1B4018FB9BAD3 on mainnet. Estimated Gas Cost: 372220  (gas limit: 3000000, gas price: 0.025000000000000001387778780781445675529539585113525390625)
  2024-03-04 11:14:45,435 - 9162 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1709522085.0, "order_id": "add-OSMO-USDC-1709522066976880", "exchange_order_id": "C22897750551744A141409CC4AE0B9A8AB9638FBB5622FC22CA1B4018FB9BAD3", "order_action": "LPType.ADD", "trading_pair": "OSMO-USDC", "fee_tier": "MEDIUM", "lower_price": "1.598674952860452", "upper_price": "1.614742037813823", "amount": "0.500000", "creation_timestamp": 1709522066.0, "token_id": 0, "event_name": "RangePositionUpdateEvent", "event_source": "osmosis_osmosis_mainnet"}
  2024-03-04 11:14:46,417 - 9162 - GatewayOsmosisAMMLP - ERROR - 'txStatus'
  Traceback (most recent call last):
    File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 1119, in _status_polling_loop
      await safe_gather(
    File "/Users/rapcomia/github/hummingbot/6685/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
      return await asyncio.gather(*args, **kwargs)
    File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 880, in update_order_status
      if update_result["txStatus"] == 1:
  KeyError: 'txStatus'
  2024-03-04 11:14:48,041 - 9162 - GatewayOsmosisAMMLP - ERROR - 'txStatus'
  Traceback (most recent call last):
    File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 1119, in _status_polling_loop
      await safe_gather(
    File "/Users/rapcomia/github/hummingbot/6685/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
      return await asyncio.gather(*args, **kwargs)
    File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 880, in update_order_status
      if update_result["txStatus"] == 1:
  KeyError: 'txStatus'
  ```

[logs_ammlp-osmo.log](https://github.com/hummingbot/gateway/files/14476114/logs_ammlp-osmo.log)

2024-03-06 23:30 UTC, chasevoorhees commented
Sorry this one is taking bit longer than expected; the good news is that I finally reconciled the tokenId == poolId || positionId issue. 

Basically, tokenId can be either poolId || positionId and I just figure out which on the backend once reduceLiquidity() is called.

This means we'll support multiple CL positions for the same pool (GAMM positions are all strictly 1 per pool though).


I'll update later tonight and will hopefully have finished re-testing everything by then.

2024-03-07 11:37 UTC, rapcmia commented
Thanks for the update @chasevoorhees, 
- Issue reported for `KeyError: 'txStatus'` has been fixed 🚀 
- Ran another test on endpoints, all ok 
- Ran another amm-lp strategy:
  - Successfully created liqudity but getting `KeyError: 'lowerPrice'` 
  ![image](https://github.com/hummingbot/gateway/assets/73840223/2fdb4d89-d484-4c48-8325-602300a7f051)
    ```
    2024-03-07 19:28:05,359 - 30085 - hummingbot.client.hummingbot_application - INFO - start command initiated.
    2024-03-07 19:28:05,505 - 30085 - GatewayOsmosisAMMLP - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
    2024-03-07 19:28:06,002 - 30085 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - WARNING - osmosis_osmosis_mainnet connector is not ready. Please wait...
    2024-03-07 19:28:07,001 - 30085 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - WARNING - osmosis_osmosis_mainnet connector is not ready. Please wait...
    2024-03-07 19:28:08,001 - 30085 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - INFO - osmosis_osmosis_mainnet connector is ready. Trading started.
    2024-03-07 19:28:11,236 - 30085 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
    2024-03-07 19:28:12,880 - 30085 - hummingbot.strategy.amm_v3_lp.amm_v3_lp - INFO - Creating new position over 1.74170867230967679248090 to 1.75921328208163334315910 price range. [clock=2024-03-07 11:28:12+00:00]
    2024-03-07 19:28:33,453 - 30085 - GatewayOsmosisAMMLP - INFO - Created ADD liquidity order add-OSMO-USDC-1709810892880608 txHash: 144F05F523831F9B9ED30336A03EEDF13CA4A0B4353F067DD73D84ABAB2CA67A on mainnet. Estimated Gas Cost: 372031  (gas limit: 2000000, gas price: 0.025000000000000001387778780781445675529539585113525390625)
    2024-03-07 19:28:33,454 - 30085 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1709810913.0, "order_id": "add-OSMO-USDC-1709810892880608", "exchange_order_id": "144F05F523831F9B9ED30336A03EEDF13CA4A0B4353F067DD73D84ABAB2CA67A", "order_action": "LPType.ADD", "trading_pair": "OSMO-USDC", "fee_tier": "MEDIUM", "lower_price": "1.741708672309676", "upper_price": "1.759213282081633", "amount": "0.500000", "creation_timestamp": 1709810892.0, "token_id": 0, "event_name": "RangePositionUpdateEvent", "event_source": "osmosis_osmosis_mainnet"}
    2024-03-07 19:28:34,829 - 30085 - GatewayOsmosisAMMLP - INFO - Liquidity added for position with ID 1.
    2024-03-07 19:28:34,835 - 30085 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1709810914.0, "order_id": "add-OSMO-USDC-1709810892880608", "exchange_order_id": "144F05F523831F9B9ED30336A03EEDF13CA4A0B4353F067DD73D84ABAB2CA67A", "trading_pair": "OSMO-USDC", "lower_price": "1.741708672309676", "upper_price": "1.759213282081633", "amount": "0", "fee_tier": "MEDIUM", "creation_timestamp": 1709810892.0, "trade_fee": {"percent": "0", "percent_token": null, "flat_fees": [{"token": "OSMO", "amount": "0.000009300775000000000516296727593"}]}, "token_id": 1, "event_name": "RangePositionLiquidityAddedEvent", "event_source": "osmosis_osmosis_mainnet"}
    2024-03-07 19:28:39,962 - 30085 - GatewayOsmosisAMMLP - ERROR - 'lowerPrice'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 1079, in _status_polling_loop
        await safe_gather(
      File "/Users/rapcomia/github/hummingbot/6685/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
        return await asyncio.gather(*args, **kwargs)
      File "/Users/rapcomia/github/hummingbot/6685/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py", line 955, in update_nft
        lower_price = Decimal(nft_update_result["lowerPrice"])
    KeyError: 'lowerPrice'
    ```

[logs_ammlp-osmo.log](https://github.com/hummingbot/gateway/files/14523391/logs_ammlp-osmo.log)

2024-03-12 03:25 UTC, chasevoorhees commented
@rapcmia 

The above has been fixed. I fear there still may be testing needed on the strat (collectFees and removeLiquidity specifically) but I'll have @nkhrs help me test those tonight.

2024-03-12 06:39 UTC, rapcmia commented
Thanks for the update @chasevoorhees 
- Issue for `KeyError: 'lowerPrice'` has been fixed ✅ 
- Observed that after created/added liquidity
    - There are no active positions on `status`
    - It kept on creating/addng positions on pool to Osmosis exchange 
      ![image](https://github.com/hummingbot/gateway/assets/73840223/9d894b15-8f99-4163-ae5a-93d4a71547a2)
      ![image](https://github.com/hummingbot/gateway/assets/73840223/9fe627a0-b0b5-4cc1-b0f8-db918dda3048)

2024-03-13 03:51 UTC, chasevoorhees commented
@rapcmia 

Been running it through debug and I'm somewhat confused on how the order tracking with the client works

Here's what gateway_evm_amm_lp is doing:

```    async def update_order_status(self, tracked_orders: List[GatewayInFlightLPOrder]):
...
            if update_result["txStatus"] == 1:
...
                self.stop_tracking_order(tracked_order.client_order_id)

```

I'm assuming that txStatus==1 means the transaction was confirmed. I'm copying this behavior, and thus we're ending our order tracking right after Osmosis accepts the position. 

So - when EVM positions run, every time we hit this:
self.logger().info(f"Liquidity added for position with ID...
they call stop_tracking_order()

Consequently, the position is never picked up by status since it's removed right after it's confirmed... 

Anyway - still looking at this. Will try to get some more advice.

2024-03-15 04:29 UTC, rapcmia approved these changes
- Setup this PR with https://github.com/hummingbot/hummingbot/pull/6685
- Ran API tests using postman
	- GET connectors, status and connectors ok
	- POST balances, poll and tokens ok 
	- Wallet add, get and remove ok 
	- POST price, add and check position ok 
	- POST remove and collect fees ok 
- Setup on amm_lp strategy:
	- Connector available ok
	- Ran tests on LOW and MEDIUM tier
	- Modified gateway configs ok 
	- However there is ongoing issue on connector where continuously creating positions.
		- The team decided to merge this connector and create a separate ticket https://github.com/hummingbot/gateway/issues/294 for a fix
		- To be discussed for possible HIP or open community bounty

2024-03-15 04:31 UTC, merged

2024-03-15 15:28 UTC, nkhrs commented
Hi @david-hummingbot sure thing. Quick question, our current fork and branch (https://github.com/pecuniafinance/hummingbot-site/tree/doc/osmosis) contains a Connector Guide for Osmosis as well as the osmosis chain page, osmosis connector page, and updated cosmos chain page. Should I keep the guide in there or remove it and do a separate PR at a later date?

2024-03-20 08:42 UTC, nkhrs commented
Hi @david-hummingbot PR is opened for the osmosis docs https://github.com/hummingbot/hummingbot-site/pull/355/files#diff-7df430ead391ce2e8bc3db8d574c3c07a798bdb7ab2cbe53fde7e3eb4857158b

Cheers