update bnb token list
hummingbot/gateway pull request #99
Opened 2023-05-03 13:05 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr updates the BNB token list with data from the token list used by Pancakeswap.

**Tests performed by the developer**:
--

**Tips for QA testing**:
- Test a normal instance of Pancake swap connector.

2023-05-03 13:26 UTC, rapcmia approved these changes

2023-05-03 14:05 UTC, fengtality requested changes
Approved subject QA testing that the top tokens on BNB Chain (WBNB, USDT, USDC, CAKE) don't have any duplicate entries in this list, since if there are duplicates, the token symbol may resolve to the incorrect address.

2023-05-03 14:05 UTC, fengtality approved these changes

2023-05-04 06:46 UTC, rapcmia commented
> Approved subject QA testing that the top tokens on BNB Chain (WBNB, USDT, USDC, CAKE) don't have any duplicate entries in this list, since if there are duplicates, the token symbol may resolve to the incorrect address.

Confirmed no duplicate and token symbols and address are correct 💯

2023-05-05 05:13 UTC, merged

2023-05-05 05:13 UTC, rapcmia commented
Merged to development and will be available on hummingbot version 1.16.0